---
title: "In-Class Ex06"
description: |
  In-Class Exercise 06
author:
  - name: Wang Tianqi
    
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, evaluation = TRUE, message = FALSE, warning = FALSE, fig.retina = 3)

```

# Getting Started

## Setting up R packages



```{r}
packages = c('tidyverse', 'sf', 'tmap', 'lubridate', 'clock', 'sftime', 'rmarkdown')

for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
}

```

## Importing data

```{r}
schools <- read_sf("data/Schools.csv", 
                   options = "GEOM_POSSIBLE_NAMES=location")

print(schools)


buildings <- read_sf("data/buildings.csv", 
                   options = "GEOM_POSSIBLE_NAMES=location")

print(buildings)

pubs <- read_sf("data/pubs.csv", 
                   options = "GEOM_POSSIBLE_NAMES=location")

apartments <- read_sf("data/apartments.csv", 
                   options = "GEOM_POSSIBLE_NAMES=location")

employers <- read_sf("data/employers.csv", 
                   options = "GEOM_POSSIBLE_NAMES=location")

restaurants <- read_sf("data/restaurants.csv", 
                   options = "GEOM_POSSIBLE_NAMES=location")
```

## 

### 

```{r}
tmap_mode("view")
tm_shape(buildings)+
tm_polygons(col = "grey60",
           size = 1,
           border.col = "black",
           border.lwd = 1)


```

```{r}
tmap_mode("view")
#tmap_mode("plot")
tm_shape(buildings)+
tm_polygons(col = "grey60",
           size = 1,
           border.col = "black",
           border.lwd = 1) +
tm_shape(employers) +
  tm_dots(col = "red")+
tm_shape(schools) +
  tm_dots(col = "yellow")+
tm_shape(pubs) +
  tm_dots(col = "blue")+
tm_shape(apartments) +
  tm_dots(col = "green")+
tm_shape(restaurants) +
  tm_dots(col = "purple")


```

```{r, eval=FALSE}

logs <- read_sf("data/ParticipantStatusLogs1.csv", 
                options = "GEOM_POSSIBLE_NAMES=currentLocation")


```


```{r, eval=FALSE}


logs_selected <- logs %>%
  mutate(Timestamp = date_time_parse(timestamp, zone="", format = "%Y-%m-%dT%H:%M:%S")) %>%
  mutate(day=get_day(Timestamp)) %>%
  filter(currentMode == "Transport")


write_rds(logs_selected, "data/rds/logs_selected.rds")

```


```{r}
logs_selected <- read_rds("data/rds/logs_selected.rds")

```


```{r}

tmap_mode("plot")
tm_shape(buildings)+
tm_polygons(col = "grey60",
           size = 1,
           border.col = "black",
           border.lwd = 1) +
tm_shape(logs_selected) +
  tm_dots(col = "red")


```


```{r}
hex <- st_make_grid(buildings, 
                    cellsize=100, 
                    square=FALSE) %>%
  st_sf() %>%
  rowid_to_column('hex_id')
plot(hex)

points_in_hex <- st_join(logs_selected, 
                         hex, 
                         join=st_within)

#plot(points_in_hex, pch='.')


points_in_hex <- st_join(logs_selected, 
                        hex, 
                        join=st_within) %>%
  st_set_geometry(NULL) %>%
  count(name='pointCount', hex_id)
head(points_in_hex)



hex_combined <- hex %>%
  left_join(points_in_hex, 
            by = 'hex_id') %>%
  replace(is.na(.), 0)


tm_shape(hex_combined %>%
           filter(pointCount > 0))+
  tm_fill("pointCount",
          n = 8,
          style = "quantile") +
  tm_borders(alpha = 0.1)

```

```{r}
logs_path <- logs_selected %>%
  group_by(participantId, day) %>%
  summarize(m = mean(Timestamp), 
            do_union=FALSE) %>%
  st_cast("LINESTRING")



logs_path_0 <- logs_path%>%filter(`participantId` == "0")

tmap_mode("plot")
tm_shape(buildings)+
tm_polygons(col = "grey60",
           size = 1,
           border.col = "black",
           border.lwd = 1) +
tm_shape(logs_path_0) +
  tm_lines(col = "blue")


tmap_mode("plot")
tm_shape(buildings)+
tm_polygons(col = "grey60",
           size = 1,
           border.col = "black",
           border.lwd = 1) +
tm_shape(logs_path_0) +
  tm_lines(col = "blue")+
tm_facets(by="day")


```

